name: iOS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Instalar dependências
        run: flutter pub get

      - name: Compilar iOS
        run: flutter build ipa --release --no-codesign

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: it-audit-ios
          path: build/ios/ipa/*.ipa
